version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backendcontainer
    environment:
      - MONGO_URL=mongodb://mongodb_container:27017
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    build:
      context: .
      dockerfile: database-image/Dockerfile
    container_name: mongodb_container
    ports:
      - "27017:27017"
